api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenVerifyView
)
from .views import BookViewSet, UsernameView
from rest_framework.routers import DefaultRouter

app_name = 'api'

router = DefaultRouter()
router.register(r'books', BookViewSet, basename='book')

urlpatterns = [
    path('token/', TokenObtainPairView.as_view()),
    path('verify/', TokenVerifyView.as_view()),
    path('user/', UsernameView.as_view()),
]

urlpatterns += router.urls

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path("", include("frontend.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from .views import LoginView, RegisterView, DashboardView
from .views import LogoutView, DeleteView, EditView, DetailView
from .views import CreateView, PatchView

app_name = 'frontend'

urlpatterns = [
    path("", LoginView.as_view(), name="index"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("books/", DashboardView.as_view(), name="dashboard"),
    path("book/<str:id>/", DetailView.as_view(), name="details" ),
    path("dashboard/create/", CreateView.as_view(), name="create"),
    path("delete/book/<str:id>/", DeleteView.as_view(), name="delete"),
    path("edit/book/<str:id>/", EditView.as_view(), name="update"),
    path("quick-edit/book/<str:id>/", PatchView.as_view(), name="patch"),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from backend.models import User, Book
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        exclude = ['user', 'cover']

        widgets = {
            'pubdate': DateInput(),
        }

class BookPatchForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author']

frontend/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserForm, BookForm, BookPatchForm
from django.views.generic import TemplateView
from .services import user_token_service, authenticate_service
from .services import book_list_service, book_detail_service
from .services import book_delete_service, book_create_service
from .services import book_edit_service, book_patch_service, get_username_service
from django.contrib.auth.models import Permission
from datetime import datetime

class LoginView(TemplateView):
    def get(self, request):
        auth = authenticate_service(request)

        if auth['status_code'] != 200:
            response = render(request, "login.html")
            response.delete_cookie("access")
            return response
            
        return redirect("frontend:dashboard")
        
    
    def post(self, request):
        token_payload = user_token_service(request)
        status_code = token_payload['status_code']
        data = token_payload['body']

        if status_code == 200:
            response = redirect('frontend:dashboard')
            response.set_cookie(key="access", value=data['access'], samesite="Lax")
        elif status_code == 401:
            messages.add_message(request, messages.ERROR, 
                                 "Invalid username or password. Please try again.")
            response = render(request, "login.html")
        else:
            messages.add_message(request, messages.ERROR, 
                                 "Oops! One of of your fields was left empty! Please try again.")
            response = render(request, "login.html")

        return response

class LogoutView(TemplateView):
    def get(self, request):
        response = redirect('frontend:index')
        response.delete_cookie("access")
        return response

class RegisterView(TemplateView):
    def get(self, request):
        auth = authenticate_service(request)

        if auth['status_code'] != 200:
            context = {'form': UserForm()}
            response = render(request, "register.html", context)
            return response
        
        return redirect("frontend:dashboard")
    
    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            c_book_perm = Permission.objects.get(codename="add_book")
            r_book_perm = Permission.objects.get(codename="view_book")
            u_book_perm = Permission.objects.get(codename="change_book")
            d_book_perm = Permission.objects.get(codename="delete_book")
            permissions = [c_book_perm, r_book_perm, u_book_perm, d_book_perm]
            user.save()
            user.user_permissions.set(permissions)
            return redirect("frontend:index")
        
        messages.add_message(request, messages.ERROR, 
                             "There was a problem creating your account. \
                                Make sure that you follow field requirements.")
        return render(request, "register.html")

class DashboardView(TemplateView):
    def get(self, request):

        book_list_payload = book_list_service(request)
        status_code = book_list_payload['status_code']
        data = book_list_payload['body']

        if status_code != 200:
            return redirect("frontend:index")
        
        username = get_username_service(request)
        if username is None:
            redirect("frontend:index")
        

        page_number = request.GET.get('page_number')
        items_per_page = request.GET.get('items_per_page') 
        q = request.GET.get('q') if request.GET.get('q') != None else ""
        date_from = request.GET.get('date_from') if request.GET.get('date_from') != None else ""
        date_to = request.GET.get('date_to') if request.GET.get('date_to') != None else ""

        if page_number != None or page_number != "":
            try:
                page_number = int(page_number)
            except:
                page_number = 1

        if items_per_page == None or items_per_page == "":
            try:
                items_per_page = int(items_per_page)
            except:
                items_per_page = 3

        context = {'books': data['results'],
                    'next_url_params': data['next'],
                    'prev_url_params': data['previous'],
                    'q': q,
                    'date_from': date_from,
                    'date_to': date_to,
                    'items_per_page': items_per_page,
                    'page_number': page_number,
                    'total_pages': data['count'],
                    'username': username}
        
        return render(request, "dashboard.html", context)

class DetailView(TemplateView):
    def get(self, request, id): 
        
        book_payload = book_detail_service(request, id)
        status_code = book_payload['status_code']
        data = book_payload['body']

        if status_code == 401:
            return redirect("frontend:index")  

        if status_code == 200:
            data['created'] = datetime.strptime(data['created'][:-13], '%Y-%m-%dT%H:%M:%S%f')
            context = {'book': data}
            return render(request, "book-details.html", context) 
        return redirect("frontend:dashboard")
    
class DeleteView(TemplateView):
    def get(self, request, id):
        
        delete_payload = book_delete_service(request, id)
        status_code = delete_payload['status_code']
        data = delete_payload['body']

        if status_code == 401:
            return redirect("frontend:index") 
        
        if status_code == 202:
            return redirect("frontend:dashboard")
        messages.add_message(request, messages.ERROR, data)
        return render(request, "delete-error.html")
        
class EditView(TemplateView):
    def get(self, request, id):

        book_payload = book_detail_service(request, id)
        status_code = book_payload['status_code']
        data = book_payload['body']

        if status_code == 401:
            return redirect("frontend:index") 

        if status_code == 200:
            form = BookForm(data=data)
            context = {'form': form}
            return render(request, "edit.html", context) 
        else:
            return redirect("frontend:dashboard")
    
    def post(self, request, id):
        
        create_payload = book_edit_service(request, id)
        status_code = create_payload['status_code']
        data = create_payload['body']

        if status_code == 401:
            return redirect("frontend:index") 
        
        if status_code == 200:
            return redirect("frontend:dashboard")
        else:
            form = BookForm(data=request.POST)
            context = {'form': form}
            for key, err in data.items():
                messages.add_message(request, messages.ERROR, f"{key} - {err[0]}")
            return render(request, "edit.html", context)

class CreateView(TemplateView):
    def get(self, request):  
        auth = authenticate_service(request)
        if auth['status_code'] != 200:
            return redirect("frontend:index")
        
        form = BookForm()
        context = {'form': form}
        return render(request, 'create.html', context)
    
    def post(self, request):
        
        create_payload = book_create_service(request)
        status_code = create_payload['status_code']
        data = create_payload['body']
        
        if status_code == 401:
            return redirect("frontend:index") 
        
        if status_code == 200:
            return redirect("frontend:dashboard")
        else:
            form = BookForm(data=request.POST)
            context = {'form': form}
            messages.add_message(request, messages.ERROR, data)
            return render(request, "create.html", context)
        
class PatchView(TemplateView):
    def get(self, request, id):

        book_payload = book_detail_service(request, id)
        status_code = book_payload['status_code']
        data = book_payload['body']

        if status_code == 401:
            return redirect("frontend:index") 

        if status_code == 200:
            form = BookPatchForm(data=data)
            context = {'form': form}
            return render(request, "edit.html", context) 
        
        return redirect("frontend:dashboard")
    
    def post(self, request, id):
        create_payload = book_patch_service(request, id)
        status_code = create_payload['status_code']
        data = create_payload['body']

        if status_code == 401:
            return redirect("frontend:index") 
        
        if status_code == 200:
            return redirect("frontend:dashboard")
        else:
            form = BookForm(data=request.POST)
            context = {'form': form}
            for key, err in data.items():
                messages.add_message(request, messages.ERROR, f"{key} - {err[0]}")
            return render(request, "edit.html", context)

frontend/templates/book-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <div class="card details">
        <figure>
            <img src="{{book.cover}}" alt="">
        </figure>
        {% if book.username %}
        <small>uploaded by {{book.username}} {{book.created|timesince}} ago</small>
        {% endif %}
        <h2>{{ book.title }} by {{ book.author }}</h2>
        {% if book.description %}
            <p>Description: {{book.description}}</p>
        {% endif %}
        <p>Pages: {{book.pagecount}}</p>
        <p>Publish date: {{book.pubdate}}</p>
        <div class="pagination no-margin">
            <a href="{% url 'frontend:patch' book.id %}" class="edit-btn">Quick Edit</a>
            <a href="{% url 'frontend:update' book.id %}" class="edit-btn">Advanced Edit</a>
            <a href="{% url 'frontend:delete' book.id %}" class="delete-btn">Delete</a>
        </div>
    </div>
</body>
</html>

frontend/templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <div class="user-form-container">
        <h1>Create book</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
</body>
</html>

frontend/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <nav>
        <div class="nav-cont">
            <p>Welcome {{username}}!</p>
            <form action="" method="GET">
                <div class="form-grid">
            
                    <div class="search-fields">
                        <label for="">Search</label>
                        <input type="text" name="q">
                    </div>
                    <div class="search-fields">
                        <label for="date-from">Date from</label>
                        <input type="date" name="date-from">
                    </div>
                    <div class="search-fields">
                        <label for="date-to">Date to</label>
                        <input type="date" name="date-to">
                    </div>
                    <div class="search-fields">
                        <label for="items_per_page">Items per page</label>
                        <input type="number" name="items_per_page">
                    </div>
                    <input type="submit" value="Search">
                    <a href="/" class="reset-btn"><p>Reset</p></a>
                </div>
            </form>
            <div class="flex">
                <a href="{% url 'frontend:create' %}" class='reset-btn extra'><p>Add book</p></a>
                <a href="{%url 'frontend:logout' %}" class='reset-btn extra'><p>Logout</p></a>
            </div>
        </div>
    </nav>
    <h1>Books</h1>
    {% if books %}
    <div class="grid">
        {% for book in books %}
            <div class="card max-width">
                <a href="{% url 'frontend:details' book.id %}" class="link">
                    <figure><img src="{{book.cover}}" alt=""></figure>
                    <h2><a href="{% url 'frontend:details' book.id %}">{{ book.author }}: {{ book.title }}</a></h2>
                    <small>published: {{book.pubdate}}</small>
                    {% if book.username %}
                        <small>uploaded by: {{book.username}}</small>
                    {% endif %}
                </a>
            </div>
        {% endfor %}
    </div>
        <div class="pagination">
            {% if prev_url_params is not None %}
                <a href="{%url 'frontend:dashboard' %}?{{prev_url_params}}&q={{q}}&date_to={{date_to}}&date_from={{date_from}}" class="prev edit-btn">Prev page</a>
            {% endif%}
            {% if next_url_params is not None %}
                <a href="{%url 'frontend:dashboard' %}?{{next_url_params}}&q={{q}}&date_to={{date_to}}&date_from={{date_from}}" class="next edit-btn">Next page</a>
            {% endif%}
        </div>
    {% else %}
        {%if q != ""%}
        <p class="no-books">No books were found. Maybe try something else?</p>
        {% else %}
        <p class="no-books">Currently, you have no books in your library.</p>
        {% endif %}
    {% endif %}
</body>
</html>

frontend/templates/delete-error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <h1>Delete Error</h1>
    <p>There was a problem deleting this book:</p>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <a href="{% url 'frontend:dashboard' %}">Go back to dashboard</a>
</body>
</html>

frontend/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <div class="user-form-container">
        <h1>Edit book</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
</body>
</html>

frontend/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <div class="user-form-container">
        <h1>Login</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Password">
            <input type="submit" value="Login">
        </form>
        <p>Don't have an account?</p>
        <a href="{%url 'frontend:register'%}"><input type="submit" value="Register"></a>
    </div>
</body>
</html>

frontend/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'style.css'%}">
    <title>Document</title>
</head>
<body>
    <div class="user-form-container">
        <h1>Register</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <form id="form" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password1" placeholder="Password">
            <input type="password" name="password2" placeholder="Repeat password">
            <p class="info-msg">Your password must be 8 or more symbols.</p>
            <input type="submit" value="Register">
        </form>
        <p>Already have an account?</p>
        <a href="{%url 'frontend:index'%}"><input type="submit" value="Login"></a>
    </div>
</body>
</html>